### PR TITLE
Arvick/Chap2 - Did Some Technical Changes + Addons

### PR DESCRIPTION
**Pull request by ArvickC**
Hello! Here is what I changed:

Edited some of the "Info.yml" to make it look nicer.
Added more sections to "Info.yml". `Strange Book` and `Objectives`

Fixed Typo's in "Story(Rough).md"

Added objectives in Chap2

### CODE REVIEW

**Review by WinstonLuo07 — APPROVED** [review]

**Comment by WinstonLuo07** [comment]
fern hurry up

**Comment by WinstonLuo07** [comment]
arvick made it look way better

**Comment by ArvickC** [comment]
Fern's on vacation, let her take her time!

**Comment by WinstonLuo07** [comment]
should be slacking >:( jk bro hcill

**Comment by FeeltheFern2** [comment]
What do I have to do? I’m on holiday so if you want anything done don’t
leave anything I need to look at/ interact with sorry I’m not going to
while I’m holidaying

**Comment by ArvickC** [comment]
Yeah, that's fine! Me and Winston were just figuring things out, I told him your on vaca, so your good, if you ever get more notifications like this just ignore them till you get back. Have fun! 👍

**Pull request merged**
